### PR TITLE
Add GBP in Admin drop down

### PR DESCRIPTION
**Pull request by martyshep**
Finished off adding support for GBP by adding GB Pounds as an option in Admin

### CODE REVIEW

**Comment by SimSync** [comment]
Maybe a pref for "custom" currencies is worth a thought. That way, the source hasn't to be updated every time to add a new currency.

**Comment by SimSync** [comment]
And have a look at the vstore.class.php. The currency is also defined there.

**Comment by martyshep** [comment]
I added GBP £ into vstore.class.php a while back. Only just got round to finishing off the admin pref. The idea of a custom currency is a good one.

**Comment by CaMer0n** [comment]
Great! Thanks! :+1:

**Pull request merged**
