### PR TITLE
Vstore language support

### PR DESCRIPTION
**Pull request by tgtje**
Adaptations to provide multi language use.
Tested on live : php 7.3.22 php 7 4.10 Local on php 8.01.
Already provided lang. packs for Vstore : English, Dutch, French, German.

### CODE REVIEW

**Comment by tgtje** [comment]
The 3 conflicting come from manual update the repsitory:

e header : deleted a present } as last line (should be none.
inc/admin_config_items : pattern MISSED the last hyphen now added (latest closed)issue.
vstore_class php : added a new LAN (missed).

**Comment by tgtje** [comment]
I will try to resolve the conflicts and create a new pull request.

**Comment by CaMer0n** [comment]
Thank you. Also, I think your line-breaks may be messing with the diff. It's not showing the lines changed, so it appears as if you changed every line of the files.

**Comment by tgtje** [comment]
Thank you, i will look into it.

**Comment by tgtje** [comment]
I now create a new pull request, but i can not find real changes to (as i understand) you mention by the line changes.
I use PSPad and Notepad++ as editors.
Maybe the issue lies in  'messing' that the LAN's occupy _more or less_ space due to the 'text length ?
I must confess i uploaded all files to be sure, and so accidently did replace files that were not changed at all. 
This is now corrected. (only the changed one are replaced).
Let's hope the new pull request is better

**Comment by CaMer0n** [comment]
The new pull-request was much better! Thank you!

**Pull request closed without merging**
