### PR TITLE
Fixed issue with product detail view and missing bank transfer fields

### PR DESCRIPTION
**Pull request by SimSync**
**Update e_url.php**: moved $config['product'] up in the file, because it was never reached (because of $config['subcategory'])

**Update admin_config.php**: Moved "bank_transfer_active" & "bank_transfer_details" down in the list and changed the "tab" setting for both settings to 5 (Bank transfer)
Bank Transfer tab was empty before...

**Implemented additional optional fields to the checkout page.**: Added in total 4 optional fields to the checkout page (2 textboxes, 2 checkboxes), which will be saved to the "shipping notes" field (without overwriting it). They can be used to force the user to e.g. confirm the terms of service, request specific information (e.g. account name), etc.
Added also an optional confirmation message to make sure the customer is aware the he is really ordering now and to give him still the option to cancel this process.

**Fix for white colored h3, h5 on cart in some themes**: Some themes use different colors for h3 and h5 tags (e.g. white), which make it hard to read them on the shopping cart.

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you! :+1:

**Comment by CaMer0n** [comment]
@SimSync I have committed your changes, but have cleaned up the preferences. Please submit a new PR which uses the prefs on the frontend as they are now stored. Thank you.

**Comment by SimSync** [comment]
@CaMer0n Done 👍

**Comment by CaMer0n** [comment]
Excellent! Thanks. :+1:

**Pull request merged**
