### PR TITLE
Rearranging the order of categories #12

### PR DESCRIPTION
**Pull request by Jimmi08**

### CODE REVIEW

**Comment by Norwayman** [comment]
Yes the rearranging of categories works great. The thing I really wanted is exactly like the SiteLinks where one can have a parent category with multiple sub-categories under those main categories. I would really like to have that you can rearrange directly from one sub-category to another sub-category if you understand what I mean. Like it is now I need to go on each file I want to change EDIT --> Change the main category. Other than my crazy wish this works great.

**Comment by Jimmi08** [comment]
Why update my fork automatically create pull request here?

**Comment by CaMer0n** [comment]
@Jimmi08 I don't know. Please take a look at form_admin.php - it does ordering without so much added code.

**Comment by Norwayman** [comment]
@Jimmi08 @CaMer0n After the last change to order ala sitelinks not all my category pages show up.
Page 2 and 3 are empty. I have a lot more categories than what is on page 1 (screenshot).

For example ARTICULOS DE OFICINA has 4 subcategories and on this screenshot there are only 2.

The frontend of the Vstore is still intact with all the sub-categories.

notallcategorypagesshow

**Comment by Jimmi08** [comment]
I can't find any file with that name. That code is from links.php, It should solve filtering and batch options too. I didn't want to pull it here, it was just try.  Don't merge it, please.

**Comment by CaMer0n** [comment]
@Jimmi08 `/e107_plugins/forum/forum_admin.php` . Yes, I think the code in links.php is more than is needed.

**Comment by Norwayman** [comment]
I have 7 main categories with a total of 16 under categories! haha
If you want, and it is better....we can maybe continue in the Vstore chatroom?

**Comment by Jimmi08** [comment]
@CaMer0n so complicated $listQry is related to the order thing? Otherwise it really looks a lot of simplier. But it looks like just 2 level category system, with sitelinks you can have more.

**Comment by Norwayman** [comment]
@Jimmi08 @CaMer0n As I understand it Boostrap default is not more than 2 levels?

**Comment by Jimmi08** [comment]
@Norwayman I suppose that 2 levels are about navigation (dropdown level), not about category system.

**Comment by CaMer0n** [comment]
@Jimmi08 Yes, the frontend code only supports 2-levels at this time. And yes, the listQry does do a lot of the work.

**Comment by Jimmi08** [comment]
@CaMer0n You would be surprised, frontend of vstore can manage 3 levels - it was first I had checked.

**Pull request closed without merging**
