### PR TITLE
Invoices (PDF & Email), Guest orders

### PR DESCRIPTION
**Pull request by SimSync**
## Invoices (PDF & Email) #61 

- Invoices will be generated on order save (saveTransaction)
- Generated invoices will be saved as pdf in sub-folder invoices
- Invoices will be attached to emails when order in status *N*ew, *C*omplete, *P*rocessing
- In case there is the need to "update" a invoice, it can be done via admin. Edit order, mark the checkbox near the invoice nr and lick update. The invoice will be recreated based on the current order data.
- Included creation date time in invoice footer

## Guest purchases #75
- Implemented a solution to allow guest purchases (Guest will be able to choose if he want's to create a user account, login to an existing account or continue as a guest)

## Customer dashboard #77 
Added a first version of the dashboard.
grafik
- Dashboard menu with the various areas (still incomplete)
- List orders of the customer.
- Show order details.
- Enable the user to cancel an order (when in state "New", "Processing", "On Hold").
- An email will be send to the customer after cancellation, informing about this change.

## Various changes / fixes
- Fixed issue, where the order status could not be inline edited in admin
- Fixed an issue, where the "Order complete" message wasn't displayed at all

## Documentation
As i don't have push access to the original vstore wiki and i have no clue if it would work (with PR) if i create a wiki on my fork, i decided to create a subfolder (wiki) and to start documenting (*.md files) here ...
Maybe there is an easier ways of doing it. In that case, I'll change it.

### CODE REVIEW

**Comment by CaMer0n** [comment]
Nice work @SimSync !

 For saving the PDF invoices, they should be saved in the Media Folder. 
You can retrieve the folder using this method: 

    e107::getFile()->getUserDir(null, true); 

When no USERID is provided, it will return a generic folder for the plugin.. ie. 'e107_media/hashxxx/vstore/'

**Comment by SimSync** [comment]
@CaMer0n Updated
BTW: is there a "clean" way to get the absolute path to the media folder? I did it now the following way:
`str_replace(array("..\\", "../"), '', e_ROOT . e107::getFile()->getUserDir($data['userid'], true));`

It happened, when using `e107::getFile()->getUserDir` from the admin area, that it returned a path starting with `../../e107_media/blablabla`. But when called from a public url e.g. "/vstore/invoice/11" it returns e107_media/blablabla` ...

**Comment by SimSync** [comment]
@cameron No, downloading works fine with the relative path out of this function. I need an absolute path just for the PDF plug in, because the class that is doing the work TCPDF is in another folder and the relative path does not match. At least this is my theory why it fails.
Nevertheless, I'll have to do more research on this to avoid to much hacking around.
Was just curious if there is a core function to get the absolute path. I check it today and fix it.

**Comment by SimSync** [comment]
@CaMer0n OK, i think i finally found a clean solution:
```
$pdf->pdf_path = realpath(e107::getFile()->getUserDir($data['userid'], true));

if ($pdf->pdf_path == false || trim($pdf->pdf_path) == '')
{
	e107::getMessage()->addError('Unable to create invoice user folder!', 'vstore');
	return;
}
```

I'm using `realpath()` now, as it translates an existing relative path to an absolute path. And because i'm calling `getUserDir($data['userid'], true)` with the `true` as second parameter, the path will be created and therefore exists and `realpath()` can resolve the path.

The if clause after that statement is only to make sure to render an error message, in case the user folder could not be created for some reasons.

**Comment by CaMer0n** [comment]
@SimSync Excellent! Thanks. :+1:

**Pull request merged**
